// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moqlqadfpwubfhymeoqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vcWxxYWRmcHd1YmZoeW1lb3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTA0MzgsImV4cCI6MjA3MzQyNjQzOH0.wLa1J8z3T86hqwTbeRN6x7f9NCFJxy2grUGRe6ghyno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});